version: '3.4'

services:
  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: usersDb
    ports:
      - "5432:5432"
    volumes:
      - ./docker-storage/databasedata:/var/lib/postgresql/data/

  backend:
    image: backend
    restart: on-failure
    build:
      context: ..
      dockerfile: ./backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    ports:
      - "5000:80"
    depends_on:
      - database
        
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
        
  client:
    image: client
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - "REACT_APP_BASE_URL=/api/"